name: pchook
services:
  server:
    image: ghcr.io/moifort/pchook:main
    container_name: pchook-server
    restart: unless-stopped
    cpu_shares: 50
    deploy:
      resources:
        limits:
          memory: 256M
    hostname: pchook
    pull_policy: always
    logging:
      driver: json-file
      options:
        max-size: 1m
    environment:
      HOST: 0.0.0.0
      PORT: "3000"
      NITRO_API_TOKEN: changeme
      NITRO_HARDCOVER_API_TOKEN: ""
      NITRO_SENTRY_DSN: ""
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - type: bind
        source: /DATA/AppData/pchook
        target: /app/.data
    network_mode: bridge
    labels:
      icon: https://raw.githubusercontent.com/moifort/pchook/main/icon.png
    ports:
      - target: 3000
        published: "3000"
        protocol: tcp

x-casaos:
  author: moifort
  category: Utilities
  icon: https://raw.githubusercontent.com/moifort/pchook/main/icon.png
  index: /
  port_map: "3000"
  scheme: http
  store_app_id: pchook
  title:
    en_us: Pchook
