name: Renovate Automerge

on:
  pull_request_target:

permissions:
  pull-requests: write

jobs:
  automerge:
    if: github.actor == 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
      - run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
